### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by ealdwairi** [anil614sagar/apigee2openapi#14]
Hello,
I used it before few years back and worked like a charm. now I believe many libs are deprecated. is this tool not maintained any more...
or anyone can help me with this error plz, thanks in advance:

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/usr/local/lib/node_modules/apigee2openapi/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/apigee2openapi/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/apigee2openapi/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18

**Comment by kurtkanaskie** [comment]
Fixed in 0.1.10
